apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broken-app
spec:
  rules:
    - host: {{ .Release.Namespace }}-broken.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: some-service
                port:
                  number: 8080