apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: broken-app
spec:
  podSelector:
    matchLabels:
      app: broken-app
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: rke2-ingress-nginx
            app.kubernetes.io/name: rke2-ingress-nginx
      ports:
        - protocol: UDP
          port: 8080